# -*- coding: utf-8 -*-
"""Flask.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W2O6s43rrCT9adOQpwMppXS4RboEfhLi
"""

!pip3 install flask_ngrok

from flask import Flask
from flask_ngrok import run_with_ngrok

app = Flask(__name__)
run_with_ngrok(app)
@app.route('/')

def home():
     return "Hello Flask!"

if __name__ == '__main__':
     app.run()

